name: django-pgbulk
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pip:
    - poetry>=1.2
variables:
  DATABASE_URL: "postgres://postgres@localhost:5432/pgbulk_local"
  EXEC_WRAPPER: ""
